name: flutnet_counter
description: A new flutter module project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutnet_counter_bridge:
    path: ../flutnet_counter_bridge
flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.companyname.flutnet_counter
    iosBundleIdentifier: com.companyname.flutnetCounter
...
