name: flutnet_flare
description: A new flutter module project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flare_flutter: ^2.0.6
  flare_dart: ^2.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutnet_flare_bridge:
    path: ../flutnet_flare_bridge
flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
  assets:
    - assets/
  module:
    androidX: true
    androidPackage: com.companyname.flutnet_flare
    iosBundleIdentifier: com.companyname.flutnetFlare

